- name: Allow postgres trust authentication
  lineinfile:
    path: /etc/postgresql/18/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local all postgres trust'
  become: true

- name: Allow all local users trust auth
  lineinfile:
    path: /etc/postgresql/18/main/pg_hba.conf
    regexp: '^local\s+all\s+all\s+peer'
    line: 'local all all trust'
  become: true
- name: Restart PostgreSQL post pg_hba change
  service:
    name: postgresql@18-main
    state: restarted
  become: true

- name: Create application database
  community.postgresql.postgresql_db:
    name: app_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    

- name: Create user database
  community.postgresql.postgresql_db:
    name: user_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql


- name: Create audit database
  community.postgresql.postgresql_db:
    name: audit_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    
  
- name: Create user schema tables
  community.postgresql.postgresql_query:
    db: user_db
    query: |
      CREATE TABLE IF NOT EXISTS users (
          user_id SERIAL PRIMARY KEY,
          username TEXT UNIQUE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS roles (
          role_id SERIAL PRIMARY KEY,
          role_name TEXT UNIQUE NOT NULL
      );

      CREATE TABLE IF NOT EXISTS user_roles (
          user_id INT REFERENCES users(user_id),
          role_id INT REFERENCES roles(role_id),
          PRIMARY KEY (user_id, role_id)
      );
   

- name: Create application schema tables
  community.postgresql.postgresql_query:
    db: app_db
    query: |
      CREATE TABLE IF NOT EXISTS applications (
        app_id SERIAL PRIMARY KEY,
        app_name TEXT NOT NULL
         );

        CREATE TABLE IF NOT EXISTS transactions (
          txn_id SERIAL PRIMARY KEY,
          app_id INT REFERENCES applications(app_id),
          amount NUMERIC
          );
   

- name: Create audit schema tables
  community.postgresql.postgresql_query:
    db: audit_db
    query: |
      CREATE TABLE IF NOT EXISTS audit_logs (
        log_id SERIAL PRIMARY KEY,
        user_id INT,
        action TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
       );

- name: Clean up app_db tables
  community.postgresql.postgresql_query:
     db: app_db  
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       TRUNCATE applications, transactions RESTART IDENTITY CASCADE;
- name: Clean up user_db tables
  community.postgresql.postgresql_query:
     db: user_db  
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       TRUNCATE users, roles, user_roles RESTART IDENTITY CASCADE;
  
- name: Clean up audit_db tables
  community.postgresql.postgresql_query:
     db: app_db  
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       TRUNCATE audit_logs RESTART IDENTITY CASCADE;
 
- name: Insert sample data into applications
  community.postgresql.postgresql_query:
    db: app_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    query: |
      INSERT INTO applications (app_name)
      SELECT 'App_' || i
      FROM generate_series(1,10) s(i)
      ON CONFLICT DO NOTHING;
      
- name: Insert sample data into transactions
  community.postgresql.postgresql_query:
    db: app_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    query: |
      INSERT INTO transactions (app_id, amount)
      SELECT (random()*9+1)::int, (random()*1000)::numeric
      FROM generate_series(1,10)
      ON CONFLICT DO NOTHING;

- name: Insert sample users
  community.postgresql.postgresql_query:
    db: user_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    query: |
      INSERT INTO users (username)
      SELECT 'user_' || i
      FROM generate_series(1,10) s(i)
      ON CONFLICT DO NOTHING;
      
- name: Insert sample roles
  community.postgresql.postgresql_query:
    db: user_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    query: |
      INSERT INTO roles (role_name)
      SELECT 'role_' || i
      FROM generate_series(1,10) s(i)
      ON CONFLICT DO NOTHING;

- name: Insert sample user-role mappings
  community.postgresql.postgresql_query:
    db: user_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    query: |
      INSERT INTO user_roles (user_id, role_id)
      SELECT u.user_id, r.role_id
      FROM users u
      JOIN roles r ON u.user_id = r.role_id
      LIMIT 10
      ON CONFLICT DO NOTHING;

- name: Insert sample audit logs
  community.postgresql.postgresql_query:
    db: audit_db
    login_user: postgres
    login_unix_socket: /var/run/postgresql
    query: |
      INSERT INTO audit_logs (user_id, action)
      SELECT i, 'ACTION_' || i
      FROM generate_series(1,10) s(i)
      ON CONFLICT DO NOTHING;
- name: Create Data Directory
  file:
    path: "{{ data_path }}"
    state: directory
    mode: '0755'
- name: Copy All csv files
  copy:
    src: "{{ item }}"
    dest: "{{ data_path }}/{{ item}}"
  loop:
    - applications.csv
    - users.csv
    - roles.csv
    - audit_logs.csv
    - user_roles.csv

- name: Load Applications data
  community.postgresql.postgresql_query:
     db: app_db
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       COPY applications(app_name) FROM '{{ data_path}}/applications.csv' 
       DELIMITER ','
       CSV HEADER;

- name: Load Users data
  community.postgresql.postgresql_query:
     db: user_db
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       COPY users(username) FROM '{{ data_path}}/users.csv' 
       DELIMITER ','
       CSV HEADER;

- name: Load roles data
  community.postgresql.postgresql_query:
     db: user_db
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       COPY roles(role_name) FROM '{{ data_path}}/roles.csv' 
       DELIMITER ','
       CSV HEADER;

- name: Load User Role mapping
  community.postgresql.postgresql_query:
     db: user_db
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       COPY user_roles(user_id, role_id)FROM '{{ data_path}}/user_roles.csv' 
       DELIMITER ','
       CSV HEADER;

- name: Load Audit Log
  community.postgresql.postgresql_query:
     db: audit_db
     login_user: postgres
     login_unix_socket: /var/run/postgresql
     query: |
       COPY audit_logs(user_id, action)FROM '{{ data_path}}/audit_logs.csv' 
       DELIMITER ','
       CSV HEADER;


 
