- name: Install PostgreSQL Python dependencies (Debian/Ubuntu)
  apt:
    name:
      - python3-psycopg2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes


- import_tasks: install_rhel.yml
  when: ansible_os_family == "RedHat"

- import_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: configure_pgdata.yml

- import_tasks: initdb.yml

- import_tasks: service.yml

- import_tasks: database.yml

- import_tasks: pg_hba.yml
