name: AutomateOps Deployment
on:
  push:
     paths:
       - 'vars/**'
       - 'inventory/**'
       - 'playbooks/**'
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Install Ansible
         run: |
           sudo apt update
           
